// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type ComicVineIssue struct {
	ID             int64
	VolumeID       int64
	Name           sql.NullString
	IssueNumber    sql.NullString
	CoverDate      sql.NullString
	StoreDate      sql.NullString
	Description    sql.NullString
	SiteDetailUrl  sql.NullString
	ImageSmallUrl  sql.NullString
	ImageMediumUrl sql.NullString
	ImageLargeUrl  sql.NullString
}

type ComicVineVolume struct {
	ID            int64
	Name          string
	StartYear     sql.NullString
	PublisherName sql.NullString
	SiteDetailUrl sql.NullString
}

type ParsedFilename struct {
	ID                 int64
	ProcessingResultID int64
	OriginalFilename   string
	Title              string
	IssueNumber        string
	Year               sql.NullString
	Publisher          sql.NullString
	VolumeNumber       sql.NullString
	Confidence         string
	Notes              sql.NullString
}

type ProcessingResult struct {
	ID               int64
	Filename         string
	Success          bool
	Error            sql.NullString
	ProcessedAt      time.Time
	ProcessingTimeMs int64
	MatchConfidence  sql.NullString
	Reasoning        sql.NullString
	ComicvineID      sql.NullInt64
	ComicvineUrl     sql.NullString
}
